spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/db_order
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
